name: Build Pacify Aspire .NET App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Setup .NET
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: |
          cd PacifyAspire
          dotnet restore

      - name: Build
        run: |
          cd PacifyAspire
          dotnet build
      
