name: Build and Deploy Pacify Azure Functions

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Get Local Settings from Github Secrets
        run: |
          cd AzureFunctions/PacifyFunctions
          echo '${{ secrets.PACIFYFUNCTIONS_LOCAL_SETTINGS }}' > local.settings.json

      - name: Restore dependencies
        run: |
          cd AzureFunctions/PacifyFunctions
          dotnet restore

      - name: Build
        run: |
          cd AzureFunctions/PacifyFunctions
          dotnet build
          
      - name: Publish
        run: | 
          cd AzureFunctions/PacifyFunctions
          dotnet publish --configuration Release --output ./publish
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pacify-function-artifact
          path: AzureFunctions/PacifyFunctions/publish/
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: pacify-function-artifact
          path: ./artifact

      - name: Azure Functions Deploy
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }} 
          package: ./artifact
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Deploy Local Settings
        run: |
          echo "${{ secrets.PACIFYFUNCTIONS_LOCAL_SETTINGS }}" > ./artifact/local.settings.json
          az functionapp config appsettings set --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings local.settings.json

