name: Build and Deploy Pacify Azure Functions

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Get Local Settings from Github Secrets
        run: |
          cd AzureFunctions/PacifyFunctions
          echo '${{ secrets.PACIFYFUNCTIONS_LOCAL_SETTINGS }}' > local.settings.json

      - name: Restore dependencies
        run: |
          cd AzureFunctions/PacifyFunctions
          dotnet restore

      - name: Build
        run: |
          cd AzureFunctions/PacifyFunctions
          dotnet build
          
      - name: Publish
        run: |
          cd AzureFunctions/PacifyFunctions && dotnet publish -c Release -o $GITHUB_WORKSPACE/myapp
        
      - name: Deploy to Azure Functions
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
          package: './myapp' 


  


  #  az ad sp create-for-rbac --name "github-actions" --role contributor --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group-name} --sdk-auth

  #     - name: Deploy Local Settings
  #       run: |
  #         echo "${{ secrets.PACIFYFUNCTIONS_LOCAL_SETTINGS }}" > ./artifact/local.settings.json
  #         az functionapp config appsettings set --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings @./artifact/local.settings.json
